![ADSA Logo](http://i.imgur.com/BV0CdHZ.png?2 "ADSA Logo")

# Spring 2018 ADSA Workshop - Python Series: Advanced Machine Learning
> Workshop content by ADSA with some adaptations from: 
> http://scikit-learn.org/stable/user_guide.html

## Overview

***
Welcome to the Advanced Machine Learning workshop. Today we will go over:
* Review of K Nearest Neighbor
* Decision Trees 
* Naive Bayes


To run any block of code, type `Ctrl + ENTER`. This will execute the code and tell you the errors encountered, if there were any.
***

## Review of K Nearest Neighbor

![knn Image from Wikipedia][knni]
[knni]: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/KnnClassification.svg/500px-KnnClassification.svg.png

Let us start by importing our iris data set(https://en.wikipedia.org/wiki/Iris_flower_data_set)

In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
print(iris_dataset.feature_names)
print(iris_dataset['data'][::50])
print(iris_dataset.target_names)
print(iris_dataset['target'][::50])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
['setosa' 'versicolor' 'virginica']
[0 1 2]


Now import the train_test_split function, which will split our data into two subsets: training and testing data.

In [3]:
from sklearn.model_selection import train_test_split

### Split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0)
#print(x_train)
#print(y_train)
#print(x_test)
#print(y_test)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_train.shape)

(112, 4)
(112,)
(38, 4)
(112,)


### Why do we need to split the data into training and testing data? 
In machine learning, we generalize patterns beyond the data used to train models. Because we do not know the target values, we can not check the accuracy of our predictions in the future. Therefore, we can use a portion of training data to test our model. 

In [6]:
from sklearn.neighbors import KNeighborsClassifier

### Create classifier

In [7]:
knn = KNeighborsClassifier()

### Train with data

In [8]:
knn = knn.fit(x_train, y_train)

### Score

In [9]:
knn.score(x_test, y_test)

0.9736842105263158

### Predict

In [10]:
import numpy as np
X_new = np.array([[5, 2.9, 1, 0.2]])
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
       iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


## Decision Trees

Decision trees are one of the few models that allow users to interpret exactly why the classifier makes a decision. Under the hood, the decision tree classifer asks a series of yes or no questions. Based on the answers, the classifier will return its decision.

### Split

In [17]:
x_train, x_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'],test_size=0.32, random_state=0)

### Create classifier

In [18]:
from sklearn import tree

In [19]:
clf = tree.DecisionTreeClassifier()

### Train with data

In [20]:
clf = clf.fit(x_train, y_train)

### Score

In [21]:
clf.score(x_test, y_test)

0.9791666666666666

### Predict

In [1]:
X_new = np.array([[5, 2.9, 1, 0.2]])
prediction = clf.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
       iris_dataset['target_names'][prediction]))

NameError: name 'np' is not defined

In [23]:
import graphviz 
import pydotplus
from sklearn.externals.six import StringIO

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=iris_dataset.feature_names,
                                class_names=iris_dataset.target_names,
                                filled=True, rounded=True,
                                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('iris.pdf')

InvocationException: GraphViz's executables not found

## Excercise: Wine dataset

In [24]:
from sklearn.datasets import load_wine

In [105]:
wine_dataset = load_wine()

In [125]:
from sklearn.model_selection import LeaveOneOut
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

loo = LeaveOneOut()
A=[]
loo.get_n_splits(wine_dataset['data'])
for train_index, test_index in loo.split(wine_dataset['data']):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = wine_dataset['data'][train_index], wine_dataset['data'][test_index]
    y_train, y_test = wine_dataset['target'][train_index], wine_dataset['target'][test_index]
#     wine_clf = tree.RandomForestClassifier()
#     wine_clf = SVC(C=0.001)
    wine_clf = KNeighborsClassifier()
    wine_clf = wine_clf.fit(X_train, y_train)
    A.append(wine_clf.score(X_test, y_test))
    #print(wine_clf.score(wine_x_test, wine_y_test))
    #print(X_train, X_test, y_train, y_test)
print(np.mean(A))    

0.6966292134831461


In [126]:
# split the data using the train_test_split
wine_x_train, wine_x_test, wine_y_train, wine_y_test = train_test_split(
    wine_dataset['data'], wine_dataset['target'], test_size=0.20, random_state=0)

In [127]:
# create the decision tree classifier
wine_clf = tree.DecisionTreeClassifier()

In [128]:
# train the data using the wine dataset
wine_clf = wine_clf.fit(wine_x_train, wine_y_train)

In [129]:
# predict the class of a wine_new
wine_new = np.array([[1.6, 5.1, 3.1, 2.20, 8.8, 1.5, 0.047, 0.052, 1.15, 6.62, 0.07, 1.75,52.0]])
prediction = wine_clf.predict(wine_new)
print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
       wine_dataset['target_names'][prediction]))
print(wine_x_train.shape)
print(wine_x_test.shape)

Prediction: [2]
Predicted target name: ['class_2']
(142, 13)
(36, 13)


In [130]:
# get the score of the decision tree model
wine_clf.score(wine_x_test, wine_y_test)

0.9722222222222222

In [27]:
dot_data = tree.export_graphviz(wine_clf, out_file=None,
                                feature_names=wine_dataset.feature_names,
                                class_names=wine_dataset.target_names,
                                filled=True, rounded=True,
                                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('wine.pdf')

InvocationException: GraphViz's executables not found

## [Naive Bayes][nb] 

The first algorithm we will explore is one of the simplest, the [Naive
Bayes][nb] algorithm. Fundamentally, this algorithm is remarkably simple
and is based on the assumption of independence that a given attribute (or
feature) belongs to a specific class. Scikit learn provides several
Naive Bayes implementations, using a specific one generally depends on
the nature of the data being analyzed:

- [Gaussian Naive Bayes][gnb] 
- [Multinomial Naive Bayes][mnb] 
- [Bernoulli Naive Bayes][bnb] 

In the following code cells, we demonstrate how to perform Naive Bayes
classification by using scikit learn, in this case we use the Gaussian
Naive Bayes implementation. The standard classification process in
scikit learn is to first fit a model to the training data and to
subsequently apply this model to predict values for the testing data.
After this process, we first compute the prediction score before
displaying the confusion matrix for this algorithm.

-----
[gnb]: http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB
[mnb]: http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB
[bnb]: http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB
[nb]: https://en.wikipedia.org/wiki/Naive_Bayes_classifier

In [ ]:
# Set up Notebook
% matplotlib inline

# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# We do this to ignore several specific Pandas warnings
import warnings

## Handwritten Digits

We will explore the Naive Bayes
classification applied to handwritten digits. First we will load the
data and review some of the sample. After which, we will apply a
Multinomial Naive Bayes classification to this data and explore the
resulting predictions.

-----

In [ ]:
# We have helper code to assist in the loading and plotting of these data
import digits as hd

# We extract features (x), labels (y), and the images for plotting.
x, y, images = hd.get_data()
hd.im_plot(x, y, images)

print('Total number of samples = {0}'.format(x.shape[0]))

-----

### Classification of Image Data

Now that these data are loaded, we can apply a Naives Bayes classifier
to this problem. Below we employ a Multinomial Naive Bayes model, and
show the classification score, and the classification report.

-----

In [ ]:
import sklearn.cross_validation as cv
(x_train, x_test, y_train, y_test) = cv.train_test_split(x, y, test_size=.25)

# First, lets try Gaussain NB
from sklearn.naive_bayes import MultinomialNB

# First we construct our Classification Model
nbc = MultinomialNB()

nbc.fit(x_train, y_train);

print('Prediction Accuracy = {0:3.1f}%'.format(100*nbc.score(x_test, y_test)))

In [ ]:
# more information on the precision, recall, f1-score, and support is found here: 
# http://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html

from sklearn.metrics import classification_report

y_pred = nbc.predict(x_test)
print(classification_report(y_test, y_pred))

-----

### Model Evaluation

The Naive Bayes model performed in a reasonable manner, but what about
on completely blind data. We can test the model by _making_ new data.
Below we use methods in the helper code to make _fake_ data, in this
case images of **one** and **seven**. We display the _fake_ images, and
then the results of our model classifying these new data.

-----

In [ ]:
ones = hd.make_ones()
hd.plot_numbers(ones)

In [ ]:
print('Actual : Predicted')
for one in ones:
    print('  1    :     {0}'.format(nbc.predict([one])[0])) # You can use "one" instead of "[one]"
                                                            # But it's depreciated in newer versions of sklearn

In [ ]:
# Now test on our sevens
sevens = hd.make_sevens()
hd.plot_numbers(sevens)

In [ ]:
print('Actual : Predicted')
for seven in sevens:
    print('  7    :     {0}'.format(nbc.predict([seven])[0]))